#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_peer="0.0.1"
  jq -n --arg fogg_peer "$ver_fogg_peer" '{fogg_peer: $fogg_peer}'
}

version "$@"
