#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_peering_route="0.0.1"
  jq -n --arg fogg_peering_route "$ver_fogg_peering_route" '{fogg_peering_route: $fogg_peering_route}'
}

version "$@"
